env:
  browser: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  "prettier/prettier": "error"
}
globals: {
  wx: true,
  Page: true,
  Component: true,
  getCurrentPages: true
}
plugins:
- 'prettier'
